# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "My Life's Journey"
description: > 
   Blog on my random thoughts, tech stuffs, Machine Learning and Football!

email: ksashikumark93@gmail.com
#blog logo
logo: "/assets/images/home.png"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Sashi Kumar'
author: 'Sash'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://ksashikumar.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@ksashikumark93'

#fill in disqus shortname to use disqus
#disqus: 'ksashikumar'

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/ksashikumark93
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/sashi.kumar.8
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/ksashikumar
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://google.com/+SashiKumar08
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:

#  - icon: quora
#    url: https://www.quora.com/profile/Sashi-Kumar-1
#    desc: Follow me on Quora
